name: Build Starters

on:
  push:
    branches: ["main"]

jobs:
  build-starters:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      matrix:
        starter: ["react-passkey-auth"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: |
          pnpm install
          pnpm turbo build;
        working-directory: ./starters/${{ matrix.starter }}
