name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run tmate session for debugging"
        required: false
        default: false

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Build packages
        run: pnpm exec turbo run build --filter='./packages/*'

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Enable tmate debugging only if the workflow is manually triggered, debug_enabled is true, and the workflow failed
      - name: Setup tmate session for debugging
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 15
